# Generated by Django 5.0.6 on 2025-12-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_vendor_delete_user'),
    ]

    operations = [
    ]
