# Generated by Django 5.0.6 on 2025-11-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Unique identifier for URL.', unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_name_idx',
            old_name='name_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_price_idx',
            old_name='price_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='prod_status_idx',
            old_name='status_idx',
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='cat_active_idx'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='category'),
            preserve_default=False,
        ),
    ]
