# Generated by Django 5.0.6 on 2025-12-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_vendor_delete_user'),
        ('products', '0002_category_rename_name_idx_prod_name_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.vendor', verbose_name='vendor'),
        ),
    ]
